apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: opengemini-operator
    app.kubernetes.io/part-of: opengemini-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
