# permissions for end users to edit opengeminiclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: opengeminicluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opengemini-operator
    app.kubernetes.io/part-of: opengemini-operator
    app.kubernetes.io/managed-by: kustomize
  name: opengeminicluster-editor-role
rules:
- apiGroups:
  - opengemini.org
  resources:
  - opengeminiclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opengemini.org
  resources:
  - opengeminiclusters/status
  verbs:
  - get
