---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opengemini-operator.opengemini.org
  resources:
  - geminiclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opengemini-operator.opengemini.org
  resources:
  - geminiclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opengemini-operator.opengemini.org
  resources:
  - geminiclusters/status
  verbs:
  - get
  - patch
  - update
