apiVersion: opengemini-operator.opengemini.org/v1
kind: GeminiCluster
metadata:
  name: test004
  namespace: opengemini
spec:
  affinity:
    enablePodAntiAffinity: true
  enableSuperuserAccess: false
  monitoring:
    type: string
  paused: false
  meta:
    dataVolumeClaimSpec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
    image: registry.woqutech.com/xiewei/opengemini:v1.0.1
    replicas: 3
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
  sql:
    image: registry.woqutech.com/xiewei/opengemini:v1.0.1
    port: "8086"
    replicas: 2
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
  store:
    dataVolumeClaimSpec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
    image: registry.woqutech.com/xiewei/opengemini:v1.0.1
    replicas: 3
    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
  version: v1
